### PR TITLE
Change EmailTemplate into an HTMLText

### PR DESCRIPTION
**Pull request by JorisDebonnet**
The email template is HTML, so why not edit it in an HTMLEditor :)

### CODE REVIEW

**Comment by nyeholt** [comment]
I believe the issue is that many email clients need a hacked together HTML structure to render consistently - and the wysiwyg editor will strip the tags and structure if it's used.

**Comment by JorisDebonnet** [comment]
You mean that the email clients need <html> and <body> tags, but the wysiwyg editor would strip those out? So the current textarea format allows editors to write the html and body tags how they want. 

But that's not really the SilverStripe way is it; it actually uses the GenericEmail.ss template right now, which I suppose could be changed by overwriting `$ss_template` in `MemberConfirmationEmail`. Then developers can choose to create another email template that overwrites it, while keeping the benefits of wysiwyg in the CMS (and leaving html/body tags out of there). 

Right?

**Comment by nyeholt** [comment]
No, but then HTML emails don't really follow _any_ kind of way. For anything more than a basic layout, you'll need to use tables with styles embedded in place to get things working, many of which the wysiwyg strips out. 

Why not an extension that can be bound that does this for the user if they want to use wysiwyg instead?

```
MemberProfilePage:
  extensions:
    - WysiwygMemberProfileEmailsExtension
```

`WysiwygMemberProfileEmailsExtension::updateCMSFields` could then swap the `EmailTemplate` for the HTMLEditorField, and `WysiwygMemberProfileEmailsExtension::$db` could change the field type. 

Happy to include an extension like this (not enabled by default, but with doc on how to do so) in the module.

**Comment by JorisDebonnet** [comment]
Okay, I see what you mean. I always heavily edit the TinyMCE config on my installations because I get annoyed that it strips everything away, so I guess that's why this works for me. I'll consider creating an extension with separate TinyMCE config (although I'm not sure that's possible; perhaps SilverStripe 4 will make that easier...)

**Pull request closed without merging**
